quarkus:
  http:
    port: 3000
    so-reuse-port: true
    tcp-quick-ack: true
    tcp-cork: true
    tcp-fast-open: true
  vertx:
    prefer-native-transport: true
  mongodb:
    connection-string: mongodb://127.0.0.1:27017
    database: guild-code
  log:
    level: INFO
    min-level: CONFIG
    syslog:
      async:
        overflow: BLOCK
    handler:
      gelf:
        enable: true
        host: localhost
        port: 12201

jwt:
  enabled: false
  secret: s#cr#t2o2o

git:
  clientId: "d3a25e9930e91076515c"
  clientSecret: "aa0337d0f101032cf1e38b11b7371c23aebb6647"
  URL_GITHUB_REDIRECT: "https://github.com/login/oauth/authorize"

"%test":
  quarkus:
    http:
      port: 3000
      so-reuse-port: true
      tcp-quick-ack: true
      tcp-cork: true
      tcp-fast-open: true
    vertx:
      prefer-native-transport: true
    mongodb:
      connection-string: mongodb://127.0.0.1:27017
      database: guild-code
    log:
      level: INFO
      min-level: CONFIG
      syslog:
        async:
          overflow: BLOCK
      handler:
        gelf:
          enable: true
          host: localhost
          port: 12201
  jwt:
    enabled: false
    secret: s#cr#t2o2o
  git:
    clientId: "d3a25e9930e91076515c"
    clientSecret: "aa0337d0f101032cf1e38b11b7371c23aebb6647"
    URL_GITHUB_REDIRECT: "https://github.com/login/oauth/authorize"

"%docker":
  quarkus:
    http:
      port: 3000
      so-reuse-port: true
      tcp-quick-ack: true
      tcp-cork: true
      tcp-fast-open: true
    vertx:
      prefer-native-transport: true
    mongodb:
      connection-string: mongodb://${MONGO_USER}:${MONGO_PWD}@${MONGO_URL}/?replicaset=${MONGO_REPLICASET}&readPreference=secondaryPreferred&authSource=admin
      database: ${MONGO_DATABASE}
    log:
      level: INFO
      min-level: CONFIG
      syslog:
        async:
          overflow: BLOCK
      handler:
        gelf:
          enable: true
          host: localhost
          port: 12201
  jwt:
    enabled: false
    secret: s#cr#t2o2o
  git:
    clientId: "${clientId}"
    clientSecret: "${clientSecret}"
    URL_GITHUB_REDIRECT: "https://github.com/login/oauth/authorize"
